version: '3.9'

services:
  login-system:
    build:
      context: ./Login-System      
      dockerfile: Dockerfile       
    ports:
      - "7282:7282"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__UserDatabase=Host=postgres;Port=5432;Database=loginsystem;Username=postgres;Password=1234;
    depends_on:
      - postgres

  postgres:
    image: postgres:16
    environment:
      - POSTGRES_DB=loginsystem
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=1234
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
